现在这个代码由dummy手动维护了，目的是进行输出训练 确保写的代码有 可以加深印象

In [2]:
import numpy as np

导入后 开始测试最简单的 创建Ndarray对象

In [3]:
v1 = np.ones((3,))
v2 = np.ones((3,2))
v3 = np.ones((3,2,1))
print((v1,v2,v3))

(array([1., 1., 1.]), array([[1., 1.],
       [1., 1.],
       [1., 1.]]), array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]]))


上面的输出： 1. 代表虽然是整数 但实际上是float  ； ones接受一个指定其shape的tuple然后生成对应shape的ndarray

注意shape 和 size 的区别。 size 是里面所有元素数目 而shape是形状

In [4]:
print(v3.size)
print(v3.shape)
print(v2.size)
print(v2.shape)

6
(3, 2, 1)
6
(3, 2)


可见两个变量 size相同 但后者比前者在shape最内侧 少一个维度

In [ ]:
v4 = np.array([[1,2,3],[4,5,6]])
print(v4)
print(v4.shape)
print(v4.size)
v5 = np.array([[[3,2,1],[4,5,6],[8,9,10]],[[3,4,5],[6,7,8],[8,1,2]]])
print(v5)
print(v5.shape)
print(v5.size)
[x**2  for x in v5.shape]


[[1 2 3]
 [4 5 6]]
(2, 3)
6
[[[ 3  2  1]
  [ 4  5  6]
  [ 8  9 10]]

 [[ 3  4  5]
  [ 6  7  8]
  [ 8  1  2]]]
(2, 3, 3)
18


NameError: name 'x' is not defined

注意这个shape是从外到内。你看我们初始化时外层是2个元素的list数组，内层是3个元素的整数list， 转换为array时， **从外到内** ，依次翻译成shape的各个dim的维度， 这里外层为2， 内层为3， 则shape是 2*3

使用shift + enter 可以依次按顺序跳转并执行每个单元格
使用ctrl + enter 可以只执行该单元格 但不跳转